# Generated by Django 2.2.3 on 2019-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50)),
                ('alpha_a', models.CharField(max_length=50)),
                ('alpha_b', models.CharField(max_length=50)),
            ],
        ),
    ]
